<?php

/**
 * @file
 * The main islandora_downloadable_datastreams module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_downloadable_datastreams_menu() {
  return array(
    'admin/islandora/tools/downloadblock' => array(
      'title' => 'Islandora Downloadable Datastreams',
      'description' => 'Configure Islandora Downloadable Datastreams.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_downloadable_datastreams_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
  return $items;
}

/**
 * Implements hook_block_info(). Creates blocks.
 */
function islandora_downloadable_datastreams_block_info() {
  return array(
    'datastream_download' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Datastream download block'),
    ), 
  );
}

/**
 * Implements hook_block_view().
 */
 
function islandora_downloadable_datastreams_block_view($delta) {
  // use the utilities.inc file
  module_load_include('inc', 'islandora_downloadable_datastreams', 'includes/utilities');
  $to_render = array();
  // Get object CModel and PID - this may be repeating itself, I'm not sure.
  $object = menu_get_object('islandora_object', 2);
  $pid = $object->id;
  $ids = array();
  $ids['pid'] = $pid;
  $ids['cmodel'] = islandora_object_load($pid)->models[0];
  $dsid = "none";  
  // If object is a selected CModel, proceed - otherwise, don't render.

  if (islandora_downloadable_datastreams_show_for_cmodel($object)) {
    // Choose DSID for large images
    if ($ids['cmodel']=='islandora:sp_large_image_cmodel') {
      $dsid = variable_get('islandora_downloadable_datastreams_image_dsid', 'JP2');
    }
   // For newspapers and books, assume PDFs
    elseif ($ids['cmodel']=='islandora:newspaperIssueCModel' || $ids['cmodel']=='islandora:bookCModel') {
      // If there's no PDF datastream, do nothing. Otherwise, PDF.
      if (!$object['PDF']) {
       $dsid = "none";
      }
      else {
        $dsid = "PDF";
      }
    }
  // For audio, assume PROXY_MP3 for now. Make this configurable - either OBJ or PROXY_MP3.
    elseif ($ids['cmodel'] == 'islandora:sp-audioCModel') {
      $dsid = "PROXY_MP3";
    }

  // For video, assume MP4 datastream until we make it configurable instead.
    elseif ($ids['cmodel'] == 'islandora:sp_videoCModel') {
      $dsid = "MP4";
    }

  // Create the link if a DSID is selected
    if ($dsid != "none") {
      global $base_url;
      $label = variable_get('islandora_downloadable_datastreams_label', 'Download');
      $to_render['content'] = '<div class="downloadlink"><a href="' . $base_url . '/islandora/object/' . $pid . '/datastream/' . $dsid . '/view">' . $label . '</a></div>';
     } 
  }
  return $to_render;
}
