<?php
/**
 * @file
 * Installation hooks for Islandora Downloadable Datastreams.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_downloadable_datastreams_uninstall() {
  $vars = array(
    'islandora_downloadable_datastreams_image_dsid',
    'islandora_downloadable_datastreams_label',
    'islandora_downloadable_datastreams_selected_cmodels',
  );
  array_walk($vars, 'variable_del');
}
